import React, { useMemo, useState } from "react";
import { View, Text, StyleSheet, Pressable, ScrollView, ActivityIndicator } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter, useFocusEffect } from "expo-router";
import { useTheme } from "@/src/context/ThemeContext";
import { api } from "@/src/api";
import { CAPABILITIES, CORE_CAPABILITIES, type CapabilityKey, getEnabledCapabilities, getPersonaCapabilityDefaults, activePersonaFor } from "@/src/utils/capabilities";
import { getPersonaBaselineFeatures } from "@/src/utils/featureFlags";

export default function CustomizeFeaturesScreen() {
  const theme = useTheme(); const styles = useMemo(() => makeStyles(theme), [theme]); const router = useRouter();
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [settings, setSettings] = useState<any>({}); const [active, setActive] = useState<Set<CapabilityKey>>(new Set());
  const load = React.useCallback(async () => { try { const current = await api.getSettings(); setSettings(current); setActive(new Set(getEnabledCapabilities(current))); } catch (error) { console.warn("Failed to load capabilities", error); } finally { setLoading(false); } }, []);
  useFocusEffect(React.useCallback(() => { load(); }, [load]));
  const toggle = (key: CapabilityKey) => { if (CORE_CAPABILITIES.includes(key)) return; setActive((current) => { const next = new Set(current); if (next.has(key)) next.delete(key); else next.add(key); return next; }); };
  const reset = () => { const legacyBaseline = getPersonaBaselineFeatures(settings); if (!legacyBaseline.length) return; setActive(new Set(getPersonaCapabilityDefaults(settings))); };
  const save = async () => { setSaving(true); try { await api.updateSettings({ enabledFeatures: null, enabledCapabilities: Array.from(active) }); router.back(); } catch (error) { console.warn("Failed to save capabilities", error); } finally { setSaving(false); } };
  if (loading) return <SafeAreaView style={styles.container}><View style={styles.center}><ActivityIndicator size="large" color={theme.color.brandPrimary} /></View></SafeAreaView>;
  const groups = [{ title: "Always available", items: CAPABILITIES.filter((item) => CORE_CAPABILITIES.includes(item.key)) }, { title: "Your workspace packs", items: CAPABILITIES.filter((item) => !CORE_CAPABILITIES.includes(item.key)) }];
  return <SafeAreaView style={styles.container} edges={["top"]}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={23} color={theme.color.onSurface} /></Pressable><View style={{ flex: 1 }}><Text style={styles.headerTitle}>Workspace capabilities</Text><Text style={styles.headerSub}>Primary persona: {activePersonaFor(settings).replace(/_/g, " ")}</Text></View><Pressable onPress={save} disabled={saving} style={styles.save}>{saving ? <ActivityIndicator size="small" color="#fff" /> : <Text style={styles.saveText}>Save</Text>}</Pressable></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.intro}>Ledgr starts small and grows with your business. Turn on a complete workflow when you need it; hidden capabilities keep their data and can be restored later.</Text><View style={styles.actionRow}><Pressable onPress={reset} style={styles.action}><Ionicons name="refresh-outline" size={15} color={theme.color.brandPrimary} /><Text style={styles.actionText}>Reset to persona</Text></Pressable><Pressable onPress={() => setActive(new Set(CAPABILITIES.map((item) => item.key)))} style={styles.action}><Ionicons name="checkmark-done-outline" size={15} color={theme.color.brandPrimary} /><Text style={styles.actionText}>Enable all</Text></Pressable></View>{groups.map((group) => <View key={group.title} style={{ marginBottom: 22 }}><Text style={styles.groupTitle}>{group.title}</Text>{group.items.map((item) => { const enabled = active.has(item.key); const locked = CORE_CAPABILITIES.includes(item.key); return <Pressable key={item.key} onPress={() => toggle(item.key)} style={[styles.card, enabled && styles.cardEnabled]} accessibilityRole="switch" accessibilityState={{ checked: enabled, disabled: locked }}><View style={[styles.icon, enabled && styles.iconEnabled]}><Ionicons name={item.key === "multi_location" ? "storefront-outline" : item.key === "growth_analytics" ? "trending-up-outline" : item.key === "invoicing" ? "document-text-outline" : item.key === "inventory" ? "cube-outline" : item.key === "ai_assistant" ? "sparkles-outline" : "layers-outline"} size={20} color={enabled ? theme.color.brandPrimary : theme.color.muted} /></View><View style={{ flex: 1, marginHorizontal: 12 }}><Text style={styles.cardTitle}>{item.label}</Text><Text style={styles.cardDesc}>{item.description}</Text></View><View style={[styles.switch, enabled && styles.switchOn]}><View style={[styles.thumb, enabled && styles.thumbOn]} /></View></Pressable>; })}</View>)}</ScrollView></SafeAreaView>;
}
function makeStyles(theme: any) { return StyleSheet.create({ container: { flex: 1, backgroundColor: theme.color.surface }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, header: { flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 15, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: theme.color.border }, back: { padding: 4 }, headerTitle: { color: theme.color.onSurface, fontSize: 17, fontWeight: "800" }, headerSub: { color: theme.color.muted, fontSize: 11, marginTop: 3, textTransform: "capitalize" }, save: { backgroundColor: theme.color.brandPrimary, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 15 }, saveText: { color: "#fff", fontWeight: "800", fontSize: 12 }, content: { padding: 16, paddingBottom: 40 }, intro: { color: theme.color.muted, fontSize: 13, lineHeight: 19, marginBottom: 14 }, actionRow: { flexDirection: "row", gap: 9, marginBottom: 20 }, action: { flexDirection: "row", alignItems: "center", gap: 6, borderWidth: 1, borderColor: theme.color.border, paddingVertical: 8, paddingHorizontal: 11, borderRadius: 18 }, actionText: { color: theme.color.onSurface, fontSize: 11, fontWeight: "700" }, groupTitle: { color: theme.color.muted, fontSize: 11, fontWeight: "900", letterSpacing: 1.1, textTransform: "uppercase", marginBottom: 8 }, card: { flexDirection: "row", alignItems: "center", padding: 14, borderRadius: 17, borderWidth: 1, borderColor: theme.color.border, backgroundColor: theme.color.surfaceSecondary, marginBottom: 9 }, cardEnabled: { borderColor: theme.color.brandPrimary + "99", backgroundColor: theme.color.brandPrimary + "0D" }, icon: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: theme.color.surface }, iconEnabled: { backgroundColor: theme.color.brandPrimary + "18" }, cardTitle: { color: theme.color.onSurface, fontSize: 14, fontWeight: "800" }, cardDesc: { color: theme.color.muted, fontSize: 11, lineHeight: 15, marginTop: 3 }, switch: { width: 42, height: 24, borderRadius: 12, padding: 3, justifyContent: "center", backgroundColor: theme.color.border }, switchOn: { backgroundColor: theme.color.brandPrimary }, thumb: { width: 18, height: 18, borderRadius: 9, backgroundColor: "#fff" }, thumbOn: { alignSelf: "flex-end" } }); }
