import React, { useCallback, useEffect, useMemo, useState } from "react";
import { View, Text, StyleSheet, ScrollView, Pressable, ActivityIndicator, Share } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { fmt } from "@/src/theme";
import { useTheme } from "@/src/context/ThemeContext";
import { api } from "@/src/api";
import { printHtml } from "@/src/utils/print";
import {
  assembleMonthlyReport,
  buildMonthlyReportHtml,
  resolveReportPalette,
  money,
  type MonthlyReportData,
  type InvoiceThemeId,
} from "@/src/utils/reportDocument";

function ymOptions(count = 12): { key: string; label: string }[] {
  const opts = [];
  const now = new Date();
  for (let i = 0; i < count; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
    const label = d.toLocaleDateString(undefined, { month: "short", year: "numeric" });
    opts.push({ key, label });
  }
  return opts;
}

export default function MonthlySummary() {
  const theme = useTheme();
  const styles = useMemo(() => makeStyles(theme), [theme]);
  const router = useRouter();
  const months = useMemo(() => ymOptions(12), []);
  const [month, setMonth] = useState(months[0].key);
  const [data, setData] = useState<any>(null);
  const [report, setReport] = useState<MonthlyReportData | null>(null);
  const [invoiceTheme, setInvoiceTheme] = useState<InvoiceThemeId>("navy_gold");
  const [loading, setLoading] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [printing, setPrinting] = useState(false);
  const [error, setError] = useState("");

  const label = months.find((x) => x.key === month)?.label || month;

  const load = useCallback(async (m: string, monthLabel: string) => {
    setLoading(true); setError("");
    try {
      const [summary, dash, capital, settings] = await Promise.all([
        api.monthlySummary(m),
        api.dashboard().catch(() => ({})),
        api.capitalStatement().catch(() => ({})),
        api.getSettings().catch(() => ({})),
      ]);
      setData(summary);
      const themeId = (((settings as any)?.invoiceTheme) || "navy_gold") as InvoiceThemeId;
      setInvoiceTheme(themeId);
      setReport(assembleMonthlyReport(summary, dash, capital, settings, {
        periodTitle: monthLabel,
        savedAt: new Date().toLocaleString(),
      }));
    } catch (e: any) { setError(e.message); }
    finally { setLoading(false); }
  }, []);

  useEffect(() => { load(month, label); }, [month, label, load]);

  const buildTextSummary = () => {
    if (!data) return "";
    const lines = [
      `Ledgr — Monthly Summary`,
      `${label}`,
      ``,
      `Revenue: ${fmt(data.revenue)}`,
      `Purchases: ${fmt(data.purchases)}`,
      `Gross Profit: ${fmt(data.grossProfit)}`,
      `Drawings: ${fmt(data.drawings)}`,
      `Net Profit: ${fmt(data.netProfit)}`,
      `Cash Flow: ${fmt(data.cashFlow)}`,
      ``,
      `Transactions: ${data.salesCount} sales, ${data.billsCount} bills, ${data.paymentsCount} payments`,
    ];
    if (data.topSuppliers?.length) {
      lines.push(``, `Top Suppliers:`);
      data.topSuppliers.forEach((s: any, i: number) => lines.push(`${i + 1}. ${s.name} — ${fmt(s.amount)}`));
    }
    lines.push(``, `Generated by Ledgr`);
    return lines.join("\n");
  };

  const shareText = async () => {
    const text = buildTextSummary();
    try {
      await Share.share({ message: text, title: `Ledgr — ${label}` });
    } catch { /* user cancelled */ }
  };

  const shareAsPDF = async () => {
    if (!report) return;
    setSharing(true);
    try {
      const html = buildMonthlyReportHtml(report, invoiceTheme);
      const { uri } = await Print.printToFileAsync({ html });
      const can = await Sharing.isAvailableAsync();
      if (can) {
        await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: `Ledgr — ${label}` });
      }
    } catch (e: any) {
      setError(e.message || "PDF export failed");
    } finally { setSharing(false); }
  };

  const printReport = async () => {
    if (!report) return;
    setPrinting(true);
    try {
      const html = buildMonthlyReportHtml(report, invoiceTheme);
      await printHtml(html, `Ledgr — ${label}`);
    } catch (e: any) {
      setError(e.message || "Print failed");
    } finally { setPrinting(false); }
  };

  return (
    <SafeAreaView style={styles.container} edges={["top"]}>
      <View style={styles.headerBar}>
        <Pressable testID="btn-back-monthly" onPress={() => router.back()}>
          <Ionicons name="chevron-back" size={26} color={theme.color.onSurface} />
        </Pressable>
        <Text style={styles.headerTitle}>Monthly Summary</Text>
        <View style={{ width: 26 }} />
      </View>

      <ScrollView contentContainerStyle={{ padding: theme.spacing.lg, paddingBottom: 120 }}>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.monthRow}>
          {months.map((m) => (
            <Pressable
              key={m.key}
              testID={`month-${m.key}`}
              onPress={() => setMonth(m.key)}
              style={[styles.chip, month === m.key && styles.chipActive]}
            >
              <Text style={[styles.chipText, month === m.key && styles.chipTextActive]}>{m.label}</Text>
            </Pressable>
          ))}
        </ScrollView>

        {loading ? (
          <ActivityIndicator style={{ marginTop: 40 }} color={theme.color.brandPrimary} />
        ) : report ? (
          <>
            <ReportPreview report={report} theme={theme} styles={styles} label={label} />

            <View style={styles.actionsRow}>
              <Pressable testID="btn-share-text" onPress={shareText} style={styles.actionSecondary}>
                <Ionicons name="chatbubble-ellipses-outline" size={18} color={theme.color.brandPrimary} />
                <Text style={styles.actionSecondaryText}>Share Text</Text>
              </Pressable>
              <Pressable testID="btn-print" onPress={printReport} disabled={printing} style={styles.actionSecondary}>
                {printing ? <ActivityIndicator color={theme.color.brandPrimary} /> : <>
                  <Ionicons name="print-outline" size={18} color={theme.color.brandPrimary} />
                  <Text style={styles.actionSecondaryText}>Print</Text>
                </>}
              </Pressable>
              <Pressable testID="btn-share-pdf" onPress={shareAsPDF} disabled={sharing} style={styles.actionPrimary}>
                {sharing ? <ActivityIndicator color="#fff" /> : <>
                  <Ionicons name="document-outline" size={18} color="#fff" />
                  <Text style={styles.actionPrimaryText}>Share as PDF</Text>
                </>}
              </Pressable>
            </View>
          </>
        ) : null}

        {error ? <Text style={styles.error} testID="monthly-error">{error}</Text> : null}
      </ScrollView>
    </SafeAreaView>
  );
}

/**
 * MINI native preview of the same report layout. Uses the app theme (so it
 * respects dark/AMOLED mode on-screen) while the PDF stays print-light with
 * invoice-theme accents. Assets/Liabilities stack single-column on phone.
 */
function ReportPreview({ report, theme, styles, label }: { report: MonthlyReportData; theme: any; styles: any; label: string }) {
  const sym = report.currencySymbol;
  const hasPartners = report.partners.length > 0;
  const neg = (n: number) => Number(n) < 0;

  return (
    <View testID="report-preview">
      <Text style={styles.periodTitle}>{report.periodTitle}</Text>
      <Text style={styles.periodSub}>{report.periodStart} · Saved {report.savedAt}</Text>

      {/* Hero card */}
      <View style={styles.heroCard} testID="report-hero">
        <View style={[styles.heroRow, styles.heroRowFirst]}>
          <Text style={styles.heroNetLabel}>Net Profit</Text>
          <Text style={styles.heroNetValue}>{money(report.netProfit, sym)}</Text>
        </View>
        {hasPartners && report.partnerCount > 0 ? (
          <View style={styles.heroRow}>
            <Text style={styles.heroLabel}>Each Partner's Share{report.splitLabel ? ` (${report.splitLabel})` : ""}</Text>
            <Text style={styles.heroValue}>{money(report.partnerShareEach, sym)}</Text>
          </View>
        ) : null}
        <View style={styles.heroRow}>
          <Text style={styles.heroLabel}>Profit Before Commission</Text>
          <Text style={styles.heroValue}>{money(report.profitBeforeCommission, sym)}</Text>
        </View>
        {report.commission !== 0 || report.commissionPct > 0 ? (
          <View style={[styles.heroRow, styles.heroRowLast]}>
            <Text style={styles.heroLabel}>Commission{report.commissionPct > 0 ? ` (${report.commissionPct}%)` : ""}</Text>
            <Text style={styles.heroValue}>{money(report.commission, sym)}</Text>
          </View>
        ) : null}
      </View>

      {/* Assets */}
      <Text style={styles.sectionLabel} testID="report-assets">ASSETS</Text>
      {report.assets.map((a, i) => (
        <View key={`a${i}`} style={styles.lineRow}>
          <Text style={styles.lineLabel}>{a.label}</Text>
          <Text style={[styles.num, neg(a.amount) && styles.numNeg]}>{money(a.amount, sym)}</Text>
        </View>
      ))}
      <View style={[styles.lineRow, styles.totalRow]}>
        <Text style={[styles.lineLabel, styles.totalLabel]}>Total Assets</Text>
        <Text style={[styles.num, styles.totalNum]}>{money(report.totalAssets, sym)}</Text>
      </View>

      {/* Liabilities */}
      <Text style={[styles.sectionLabel, { marginTop: theme.spacing.lg }]} testID="report-liabilities">LIABILITIES</Text>
      {report.liabilities.length ? report.liabilities.map((l, i) => (
        <View key={`l${i}`} style={styles.lineRow}>
          <Text style={styles.lineLabel}>{l.label}</Text>
          <Text style={[styles.num, neg(l.amount) && styles.numNeg]}>{money(l.amount, sym)}</Text>
        </View>
      )) : (
        <View style={styles.lineRow}><Text style={[styles.lineLabel, { color: theme.color.muted }]}>None</Text></View>
      )}

      {/* Drawings this period */}
      {report.drawings.length ? (
        <>
          <Text style={[styles.sectionLabel, { marginTop: theme.spacing.lg }]}>DRAWINGS THIS PERIOD</Text>
          {report.drawings.map((d, i) => (
            <View key={`d${i}`} style={styles.lineRow}>
              <Text style={styles.lineLabel}>{d.label}</Text>
              <Text style={[styles.num, neg(d.amount) && styles.numNeg]}>{money(d.amount, sym)}</Text>
            </View>
          ))}
        </>
      ) : null}

      {/* Reconciliation */}
      {hasPartners ? (
        <View style={styles.reconCard} testID="report-reconciliation">
          <Text style={styles.reconHeading}>Partner Stakes Reconciliation</Text>
          {report.partners.map((pt, i) => (
            <View key={`p${i}`} style={[styles.reconPartner, i > 0 && styles.reconSep]}>
              <View style={styles.reconRow}>
                <Text style={styles.lineLabel}>{pt.name} Opening</Text>
                <Text style={styles.num}>{money(pt.opening, sym)}</Text>
              </View>
              <View style={styles.reconRow}>
                <Text style={[styles.lineLabel, styles.indent]}>+ Profit Share</Text>
                <Text style={[styles.num, { color: theme.color.success }]}>+{money(pt.profitShare, sym)}</Text>
              </View>
              <View style={styles.reconRow}>
                <Text style={[styles.lineLabel, styles.indent]}>− Drawings</Text>
                <Text style={[styles.num, { color: theme.color.error }]}>−{money(pt.drawings, sym)}</Text>
              </View>
              <View style={[styles.reconRow, styles.reconRowLast]}>
                <Text style={[styles.lineLabel, styles.totalLabel]}>{pt.name} Ending Stake</Text>
                <Text style={[styles.num, styles.totalNum, { color: theme.color.success }]}>{money(pt.ending, sym)}</Text>
              </View>
            </View>
          ))}
        </View>
      ) : null}
    </View>
  );
}

function makeStyles(theme: any) {
  const mono = "monospace";
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.color.surface },
    headerBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: theme.spacing.lg, borderBottomWidth: 1, borderBottomColor: theme.color.border, backgroundColor: theme.color.surfaceSecondary },
    headerTitle: { fontSize: 16, fontWeight: "700", color: theme.color.onSurface },
    monthRow: { gap: 8, paddingBottom: theme.spacing.md },
    chip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999, backgroundColor: theme.color.surfaceTertiary, borderWidth: 1, borderColor: theme.color.border, flexShrink: 0 },
    chipActive: { backgroundColor: theme.color.brandPrimary, borderColor: theme.color.brandPrimary },
    chipText: { color: theme.color.onSurface, fontSize: 13, fontWeight: "500" },
    chipTextActive: { color: theme.color.onBrandPrimary },

    periodTitle: { fontSize: 22, fontWeight: "800", color: theme.color.onSurface, marginTop: theme.spacing.md },
    periodSub: { color: theme.color.muted, fontSize: 12, marginTop: 4, marginBottom: theme.spacing.lg },

    heroCard: {
      backgroundColor: theme.color.successBg, borderRadius: theme.radius.lg,
      borderWidth: 1, borderColor: theme.color.divider, paddingHorizontal: theme.spacing.lg, marginBottom: theme.spacing.xl,
    },
    heroRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: theme.color.divider, gap: 12 },
    heroRowFirst: {},
    heroRowLast: { borderBottomWidth: 0 },
    heroNetLabel: { fontSize: 15, fontWeight: "700", color: theme.color.onSurface },
    heroNetValue: { fontFamily: mono, fontSize: 24, fontWeight: "800", color: theme.color.onSurface, textAlign: "right" },
    heroLabel: { fontSize: 14, fontWeight: "700", color: theme.color.onSurface, flexShrink: 1 },
    heroValue: { fontFamily: mono, fontSize: 15, fontWeight: "600", color: theme.color.onSurface, textAlign: "right" },

    sectionLabel: { fontSize: 10, fontWeight: "700", letterSpacing: 1.4, textTransform: "uppercase", color: theme.color.muted, marginBottom: 8 },
    lineRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: theme.color.divider, gap: 12 },
    lineLabel: { fontSize: 14, color: theme.color.onSurface, flexShrink: 1 },
    indent: { paddingLeft: 14, color: theme.color.muted },
    num: { fontFamily: mono, fontSize: 14, fontWeight: "600", color: theme.color.onSurface, textAlign: "right" },
    numNeg: { color: theme.color.error },
    totalRow: { borderBottomWidth: 0, borderTopWidth: 2, borderTopColor: theme.color.onSurface, marginTop: 2 },
    totalLabel: { fontWeight: "800" },
    totalNum: { fontWeight: "800" },

    reconCard: {
      backgroundColor: theme.color.surfaceSecondary, borderRadius: theme.radius.lg,
      borderWidth: 1, borderColor: theme.color.divider, padding: theme.spacing.lg, marginTop: theme.spacing.xl,
    },
    reconHeading: { color: theme.color.brandPrimary, fontWeight: "800", fontSize: 17, marginBottom: 8 },
    reconPartner: { paddingVertical: 6 },
    reconSep: { borderTopWidth: 2, borderTopColor: theme.color.divider, marginTop: 6, paddingTop: 12 },
    reconRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: theme.color.divider, gap: 12 },
    reconRowLast: { borderBottomWidth: 0 },

    actionsRow: { flexDirection: "row", gap: 8, marginTop: theme.spacing.xl },
    actionSecondary: {
      flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6,
      padding: theme.spacing.md, borderRadius: theme.radius.md,
      borderWidth: 1, borderColor: theme.color.brandPrimary, backgroundColor: theme.color.surfaceSecondary,
    },
    actionSecondaryText: { color: theme.color.brandPrimary, fontWeight: "600", fontSize: 14 },
    actionPrimary: {
      flex: 1.2, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6,
      padding: theme.spacing.md, borderRadius: theme.radius.md, backgroundColor: theme.color.brandPrimary,
    },
    actionPrimaryText: { color: "#fff", fontWeight: "600", fontSize: 14 },
    error: { color: theme.color.error, textAlign: "center", marginTop: 12, fontSize: 13 },
  });
}
