import React, { useCallback, useEffect, useMemo, useState } from "react";
import { View, Text, StyleSheet, ScrollView, Pressable, ActivityIndicator, Share } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { fmt } from "@/src/theme";
import { useTheme } from "@/src/context/ThemeContext";
import { Card } from "@/src/components/UI";
import { api } from "@/src/api";

function ymOptions(count = 12): { key: string; label: string }[] {
  const opts = [];
  const now = new Date();
  for (let i = 0; i < count; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
    const label = d.toLocaleDateString(undefined, { month: "short", year: "numeric" });
    opts.push({ key, label });
  }
  return opts;
}

export default function MonthlySummary() {
  const theme = useTheme();
  const styles = useMemo(() => makeStyles(theme), [theme]);
  const router = useRouter();
  const months = useMemo(() => ymOptions(12), []);
  const [month, setMonth] = useState(months[0].key);
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [error, setError] = useState("");

  const load = useCallback(async (m: string) => {
    setLoading(true); setError("");
    try {
      const j = await api.monthlySummary(m);
      setData(j);
    } catch (e: any) { setError(e.message); }
    finally { setLoading(false); }
  }, []);

  useEffect(() => { load(month); }, [month, load]);

  const label = months.find((x) => x.key === month)?.label || month;

  const buildTextSummary = () => {
    if (!data) return "";
    const lines = [
      `Ledgr — Monthly Summary`,
      `${label}`,
      ``,
      `Revenue: ${fmt(data.revenue)}`,
      `Purchases: ${fmt(data.purchases)}`,
      `Gross Profit: ${fmt(data.grossProfit)}`,
      `Drawings: ${fmt(data.drawings)}`,
      `Net Profit: ${fmt(data.netProfit)}`,
      `Cash Flow: ${fmt(data.cashFlow)}`,
      ``,
      `Transactions: ${data.salesCount} sales, ${data.billsCount} bills, ${data.paymentsCount} payments`,
    ];
    if (data.topSuppliers?.length) {
      lines.push(``, `Top Suppliers:`);
      data.topSuppliers.forEach((s: any, i: number) => lines.push(`${i + 1}. ${s.name} — ${fmt(s.amount)}`));
    }
    lines.push(``, `Generated by Ledgr`);
    return lines.join("\n");
  };

  const shareText = async () => {
    const text = buildTextSummary();
    try {
      await Share.share({ message: text, title: `Ledgr — ${label}` });
    } catch { /* user cancelled */ }
  };

  const shareAsPDF = async () => {
    if (!data) return;
    setSharing(true);
    try {
      const rows = (data.topSuppliers || []).map((s: any, i: number) =>
        `<tr><td>${i + 1}. ${s.name}</td><td style="text-align:right">${fmt(s.amount)}</td></tr>`).join("");
      const html = `
        <html><head><meta charset="utf-8"/>
        <style>
          body { font-family: -apple-system, sans-serif; padding: 32px; color: #1C221F; }
          h1 { color: #1C4030; margin: 0; font-size: 26px; }
          .sub { color: #8A938E; margin-bottom: 24px; }
          .kpi-row { display: flex; gap: 12px; margin-bottom: 12px; }
          .kpi { flex: 1; background: #F6F7F5; border-radius: 12px; padding: 12px; }
          .kpi-label { color: #8A938E; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
          .kpi-value { font-size: 18px; font-weight: 700; margin-top: 4px; }
          h2 { color: #1C4030; margin-top: 32px; font-size: 16px; }
          table { width: 100%; border-collapse: collapse; margin-top: 12px; }
          td { padding: 8px 0; border-bottom: 1px solid #E2E5DF; }
          .footer { margin-top: 32px; color: #8A938E; font-size: 11px; text-align: center; }
          .net { background: #1C4030; color: #fff; padding: 16px; border-radius: 12px; margin: 16px 0; }
          .net .kpi-label { color: rgba(255,255,255,0.7); }
          .net .kpi-value { color: #fff; font-size: 28px; }
        </style></head><body>
          <h1>Ledgr</h1>
          <div class="sub">Monthly Summary — ${label}</div>

          <div class="net">
            <div class="kpi-label">Net Profit</div>
            <div class="kpi-value">${fmt(data.netProfit)}</div>
          </div>

          <div class="kpi-row">
            <div class="kpi"><div class="kpi-label">Revenue</div><div class="kpi-value">${fmt(data.revenue)}</div></div>
            <div class="kpi"><div class="kpi-label">Purchases</div><div class="kpi-value">${fmt(data.purchases)}</div></div>
          </div>
          <div class="kpi-row">
            <div class="kpi"><div class="kpi-label">Gross Profit</div><div class="kpi-value">${fmt(data.grossProfit)}</div></div>
            <div class="kpi"><div class="kpi-label">Cash Flow</div><div class="kpi-value">${fmt(data.cashFlow)}</div></div>
          </div>
          <div class="kpi-row">
            <div class="kpi"><div class="kpi-label">Drawings</div><div class="kpi-value">${fmt(data.drawings)}</div></div>
            <div class="kpi"><div class="kpi-label">Transactions</div><div class="kpi-value">${data.salesCount + data.billsCount + data.paymentsCount}</div></div>
          </div>

          ${rows ? `<h2>Top Suppliers</h2><table>${rows}</table>` : ""}

          <div class="footer">Generated by Ledgr on ${new Date().toLocaleString()}</div>
        </body></html>`;

      const { uri } = await Print.printToFileAsync({ html });
      const can = await Sharing.isAvailableAsync();
      if (can) {
        await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: `Ledgr — ${label}` });
      }
    } catch (e: any) {
      setError(e.message || "PDF export failed");
    } finally { setSharing(false); }
  };

  return (
    <SafeAreaView style={styles.container} edges={["top"]}>
      <View style={styles.headerBar}>
        <Pressable testID="btn-back-monthly" onPress={() => router.back()}>
          <Ionicons name="chevron-back" size={26} color={theme.color.onSurface} />
        </Pressable>
        <Text style={styles.headerTitle}>Monthly Summary</Text>
        <View style={{ width: 26 }} />
      </View>

      <ScrollView contentContainerStyle={{ padding: theme.spacing.lg, paddingBottom: 120 }}>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.monthRow}>
          {months.map((m) => (
            <Pressable
              key={m.key}
              testID={`month-${m.key}`}
              onPress={() => setMonth(m.key)}
              style={[styles.chip, month === m.key && styles.chipActive]}
            >
              <Text style={[styles.chipText, month === m.key && styles.chipTextActive]}>{m.label}</Text>
            </Pressable>
          ))}
        </ScrollView>

        {loading ? (
          <ActivityIndicator style={{ marginTop: 40 }} color={theme.color.brandPrimary} />
        ) : data ? (
          <>
            <View style={styles.netCard} testID="monthly-net-card">
              <Text style={styles.netLabel}>Net Profit — {label}</Text>
              <Text style={[styles.netValue, { color: data.netProfit >= 0 ? "#fff" : "#FFC5BE" }]}>
                {fmt(data.netProfit)}
              </Text>
              <Text style={styles.netSub}>
                {data.salesCount} sales • {data.billsCount} bills • {data.paymentsCount} payments
              </Text>
            </View>

            <View style={styles.grid}>
              <StatCell label="Revenue" value={fmt(data.revenue)} theme={theme} styles={styles} />
              <StatCell label="Purchases" value={fmt(data.purchases)} theme={theme} styles={styles} />
              <StatCell label="Gross Profit" value={fmt(data.grossProfit)} theme={theme} styles={styles} />
              <StatCell label="Cash Flow" value={fmt(data.cashFlow)} theme={theme} styles={styles} />
              <StatCell label="Drawings" value={fmt(data.drawings)} theme={theme} styles={styles} />
              <StatCell label="Supplier Pay" value={fmt(data.supplierPayments)} theme={theme} styles={styles} />
            </View>

            {data.topSuppliers?.length > 0 && (
              <Card style={{ marginTop: theme.spacing.lg }} testID="top-suppliers-card">
                <Text style={styles.sectionTitle}>Top Suppliers</Text>
                {data.topSuppliers.map((s: any, i: number) => (
                  <View key={s.supplierId + i} style={styles.tsRow}>
                    <Text style={styles.tsRank}>{i + 1}</Text>
                    <Text style={styles.tsName}>{s.name}</Text>
                    <Text style={styles.tsAmount}>{fmt(s.amount)}</Text>
                  </View>
                ))}
              </Card>
            )}

            <View style={styles.actionsRow}>
              <Pressable testID="btn-share-text" onPress={shareText} style={styles.actionSecondary}>
                <Ionicons name="chatbubble-ellipses-outline" size={18} color={theme.color.brandPrimary} />
                <Text style={styles.actionSecondaryText}>Share Text</Text>
              </Pressable>
              <Pressable testID="btn-share-pdf" onPress={shareAsPDF} disabled={sharing} style={styles.actionPrimary}>
                {sharing ? <ActivityIndicator color="#fff" /> : <>
                  <Ionicons name="document-outline" size={18} color="#fff" />
                  <Text style={styles.actionPrimaryText}>Share as PDF</Text>
                </>}
              </Pressable>
            </View>
          </>
        ) : null}

        {error ? <Text style={styles.error} testID="monthly-error">{error}</Text> : null}
      </ScrollView>
    </SafeAreaView>
  );
}

function StatCell({ label, value, theme, styles }: any) {
  return (
    <View style={styles.stat}>
      <Text style={styles.statLabel}>{label}</Text>
      <Text style={styles.statValue}>{value}</Text>
    </View>
  );
}

function makeStyles(theme: any) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.color.surface },
    headerBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: theme.spacing.lg, borderBottomWidth: 1, borderBottomColor: theme.color.border, backgroundColor: theme.color.surfaceSecondary },
    headerTitle: { fontSize: 16, fontWeight: "700", color: theme.color.onSurface },
    monthRow: { gap: 8, paddingBottom: theme.spacing.md },
    chip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999, backgroundColor: theme.color.surfaceTertiary, borderWidth: 1, borderColor: theme.color.border, flexShrink: 0 },
    chipActive: { backgroundColor: theme.color.brandPrimary, borderColor: theme.color.brandPrimary },
    chipText: { color: theme.color.onSurface, fontSize: 13, fontWeight: "500" },
    chipTextActive: { color: theme.color.onBrandPrimary },
    netCard: { backgroundColor: theme.color.brandPrimary, borderRadius: theme.radius.lg, padding: theme.spacing.xl, marginTop: theme.spacing.md },
    netLabel: { color: "rgba(255,255,255,0.75)", fontSize: 12, textTransform: "uppercase", letterSpacing: 0.6, fontWeight: "500" },
    netValue: { color: "#fff", fontSize: 34, fontWeight: "700", marginTop: 6, letterSpacing: -1 },
    netSub: { color: "rgba(255,255,255,0.75)", fontSize: 12, marginTop: 8 },
    grid: { flexDirection: "row", flexWrap: "wrap", gap: theme.spacing.md, marginTop: theme.spacing.lg },
    stat: {
      width: "47%", flexGrow: 1,
      backgroundColor: theme.color.surfaceSecondary, borderRadius: theme.radius.md,
      padding: theme.spacing.md, borderWidth: 1, borderColor: theme.color.border,
    },
    statLabel: { fontSize: 11, color: theme.color.muted, textTransform: "uppercase", letterSpacing: 0.5, fontWeight: "500" },
    statValue: { fontSize: 18, fontWeight: "700", color: theme.color.onSurface, marginTop: 4 },
    sectionTitle: { fontSize: 15, fontWeight: "700", color: theme.color.onSurface, marginBottom: theme.spacing.md },
    tsRow: { flexDirection: "row", alignItems: "center", paddingVertical: 8, gap: 12, borderBottomWidth: 1, borderBottomColor: theme.color.divider },
    tsRank: { width: 20, color: theme.color.muted, fontWeight: "700", fontSize: 13 },
    tsName: { flex: 1, color: theme.color.onSurface, fontSize: 14 },
    tsAmount: { color: theme.color.brandPrimary, fontSize: 14, fontWeight: "700" },
    actionsRow: { flexDirection: "row", gap: 8, marginTop: theme.spacing.lg },
    actionSecondary: {
      flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6,
      padding: theme.spacing.md, borderRadius: theme.radius.md,
      borderWidth: 1, borderColor: theme.color.brandPrimary, backgroundColor: theme.color.surfaceSecondary,
    },
    actionSecondaryText: { color: theme.color.brandPrimary, fontWeight: "600", fontSize: 14 },
    actionPrimary: {
      flex: 1.2, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6,
      padding: theme.spacing.md, borderRadius: theme.radius.md, backgroundColor: theme.color.brandPrimary,
    },
    actionPrimaryText: { color: "#fff", fontWeight: "600", fontSize: 14 },
    error: { color: theme.color.error, textAlign: "center", marginTop: 12, fontSize: 13 },
  });
}
