import React, { useCallback, useState } from 'react';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ScreenHeader, Card } from '@/src/components/UI';
import { useTheme } from '@/src/context/ThemeContext';
import { api } from '@/src/api';
import { showAlert } from '@/src/utils/alerts';
import { normalizeDateInput, isValidDateString } from '@/src/utils/dateValidation';

const today = () => new Date().toISOString().slice(0, 10);
const safeDate = (value: string) => { const normalized = normalizeDateInput(value); return isValidDateString(normalized) ? normalized : value; };
function Field({ label, value, onChangeText, placeholder, keyboardType = 'default' }: any) { return <View style={{ marginBottom: 8 }}><Text style={{ fontSize: 11, fontWeight: '700', marginBottom: 4 }}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} keyboardType={keyboardType} style={{ borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 9, fontSize: 13 }} /></View>; }

export default function PlanningScreen() {
  const theme = useTheme();
  const [budgetName, setBudgetName] = useState(''); const [periodStart, setPeriodStart] = useState(today().slice(0, 8) + '01'); const [periodEnd, setPeriodEnd] = useState(today()); const [budgetId, setBudgetId] = useState(''); const [accountCode, setAccountCode] = useState('6000'); const [budgetAmount, setBudgetAmount] = useState('');
  const [country, setCountry] = useState(''); const [taxLabel, setTaxLabel] = useState(''); const [taxRate, setTaxRate] = useState(''); const [recurringAction, setRecurringAction] = useState('invoice'); const [frequency, setFrequency] = useState<'weekly' | 'monthly' | 'quarterly' | 'annual'>('monthly'); const [nextDate, setNextDate] = useState(today());
  const [budgets, setBudgets] = useState<any[]>([]); const [taxProfiles, setTaxProfiles] = useState<any[]>([]); const [recurring, setRecurring] = useState<any[]>([]); const [variance, setVariance] = useState<any[]>([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const [nextBudgets, nextTax, nextRecurring] = await Promise.all([api.listBudgets(), api.listTaxProfiles(), api.listRecurringTemplates()]); setBudgets(nextBudgets as any[]); setTaxProfiles(nextTax as any[]); setRecurring(nextRecurring as any[]); } catch { /* no active book yet */ } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const run = async (work: () => Promise<any>, message: string) => { setBusy(true); try { await work(); await load(); showAlert('Saved', message); } catch (error: any) { showAlert('Could not save', error?.message || 'Please review the fields.'); } finally { setBusy(false); } };

  return <SafeAreaView style={{ flex: 1, backgroundColor: theme.color.surface }}><ScreenHeader title="Planning and compliance" subtitle="Budgets, tax profiles, recurring work, and variance" /><ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 36 }}>
    <Card style={{ padding: 14, marginBottom: 14 }}><Text style={{ color: theme.color.brandPrimary, fontWeight: '800', fontSize: 11, textTransform: 'uppercase' }}>Budget planning</Text><Field label="Budget name" value={budgetName} onChangeText={setBudgetName} placeholder="Q1 operating plan" /><Field label="Period start" value={periodStart} onChangeText={setPeriodStart} placeholder="YYYY-MM-DD" /><Field label="Period end" value={periodEnd} onChangeText={setPeriodEnd} placeholder="YYYY-MM-DD" /><Pressable disabled={busy} onPress={() => run(() => api.createBudget({ name: budgetName, periodStart: safeDate(periodStart), periodEnd: safeDate(periodEnd) }), 'Budget created. Add an account line below.')} style={{ backgroundColor: theme.color.brandPrimary, borderRadius: 10, padding: 11 }}><Text style={{ color: '#fff', textAlign: 'center', fontWeight: '800' }}>Create budget</Text></Pressable><View style={{ height: 10 }} /><Field label="Budget ID" value={budgetId} onChangeText={setBudgetId} placeholder="Paste the budget ID" /><Field label="Account code" value={accountCode} onChangeText={setAccountCode} placeholder="6000" /><Field label="Budget amount" value={budgetAmount} onChangeText={setBudgetAmount} keyboardType="decimal-pad" placeholder="0" /><Pressable disabled={busy} onPress={() => run(() => api.addBudgetLine({ budgetId, accountCode, amount: Number(budgetAmount) }), 'Budget line added.')} style={{ backgroundColor: theme.color.surfaceSecondary, borderWidth: 1, borderColor: theme.color.brandPrimary, borderRadius: 10, padding: 11 }}><Text style={{ color: theme.color.brandPrimary, textAlign: 'center', fontWeight: '800' }}>Add budget line</Text></Pressable></Card>
    <Text style={{ fontSize: 17, fontWeight: '800', marginBottom: 8 }}>Budgets</Text>{budgets.map((budget) => <Card key={budget.id} style={{ padding: 11, marginBottom: 8 }}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Text style={{ fontWeight: '800', flex: 1 }}>{budget.name}</Text><Text style={{ fontWeight: '800' }}>{Number(budget.budget_total).toFixed(2)}</Text></View><Text style={{ color: theme.color.muted, fontSize: 11, marginTop: 3 }}>{budget.period_start} to {budget.period_end} · ID {budget.id}</Text><Pressable onPress={async () => { try { setVariance(await api.budgetVariance(budget.id) as any[]); } catch (error: any) { showAlert('Variance unavailable', error?.message || ''); } }} style={{ marginTop: 7 }}><Text style={{ color: theme.color.brandPrimary, fontSize: 11, fontWeight: '800' }}>Show variance</Text></Pressable></Card>)}
    {variance.length ? <Card style={{ padding: 12, marginBottom: 14 }}><Text style={{ fontWeight: '800', marginBottom: 5 }}>Selected budget variance</Text>{variance.map((row) => <Text key={row.account_code} style={{ color: theme.color.muted, fontSize: 11, marginTop: 3 }}>{row.account_code}: budget {Number(row.budget_amount).toFixed(2)} · actual {Number(row.actual_amount).toFixed(2)} · variance {(Number(row.budget_amount) - Number(row.actual_amount)).toFixed(2)}</Text>)}</Card> : null}
    <Card style={{ padding: 14, marginBottom: 14 }}><Text style={{ color: theme.color.brandPrimary, fontWeight: '800', fontSize: 11, textTransform: 'uppercase' }}>Tax profile</Text><Field label="Country code" value={country} onChangeText={setCountry} placeholder="IN, GB, US" /><Field label="Tax label" value={taxLabel} onChangeText={setTaxLabel} placeholder="GST / VAT / Sales tax" /><Field label="Default rate" value={taxRate} onChangeText={setTaxRate} keyboardType="decimal-pad" placeholder="0" /><Pressable disabled={busy} onPress={() => run(() => api.upsertTaxProfile({ countryCode: country, taxLabel, defaultRate: Number(taxRate) }), 'Tax profile saved locally.')} style={{ backgroundColor: theme.color.brandPrimary, borderRadius: 10, padding: 11 }}><Text style={{ color: '#fff', textAlign: 'center', fontWeight: '800' }}>Save tax profile</Text></Pressable></Card>
    <Text style={{ fontSize: 17, fontWeight: '800', marginBottom: 8 }}>Tax profiles</Text>{taxProfiles.map((profile) => <Card key={profile.id} style={{ padding: 11, marginBottom: 8 }}><Text style={{ fontWeight: '800' }}>{profile.country_code} · {profile.tax_label}</Text><Text style={{ color: theme.color.muted, fontSize: 11, marginTop: 3 }}>{profile.default_rate}% default rate</Text></Card>)}
    <Card style={{ padding: 14, marginTop: 8, marginBottom: 14 }}><Text style={{ color: theme.color.brandPrimary, fontWeight: '800', fontSize: 11, textTransform: 'uppercase' }}>Recurring work</Text><Field label="Action type" value={recurringAction} onChangeText={setRecurringAction} placeholder="invoice, expense, reminder" /><Field label="Frequency" value={frequency} onChangeText={(value: any) => setFrequency(value)} placeholder="weekly, monthly, quarterly, annual" /><Field label="Next date" value={nextDate} onChangeText={setNextDate} placeholder="YYYY-MM-DD" /><Pressable disabled={busy} onPress={() => run(() => api.createRecurringTemplate({ actionType: recurringAction, frequency, nextDate: safeDate(nextDate) }), 'Recurring template saved locally.')} style={{ backgroundColor: theme.color.surfaceSecondary, borderWidth: 1, borderColor: theme.color.brandPrimary, borderRadius: 10, padding: 11 }}><Text style={{ color: theme.color.brandPrimary, textAlign: 'center', fontWeight: '800' }}>Save recurring template</Text></Pressable></Card>
    <Text style={{ fontSize: 17, fontWeight: '800', marginBottom: 8 }}>Recurring templates</Text>{recurring.map((template) => <Card key={template.id} style={{ padding: 11, marginBottom: 8 }}><Text style={{ fontWeight: '800' }}>{template.action_type} · {template.frequency}</Text><Text style={{ color: theme.color.muted, fontSize: 11, marginTop: 3 }}>Next run: {template.next_date}</Text></Card>)}
  </ScrollView></SafeAreaView>;
}
