import React, { useCallback, useMemo, useState } from "react";
import { View, Text, StyleSheet, Pressable, ScrollView, TextInput, Alert, ActivityIndicator } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useTheme } from "@/src/context/ThemeContext";
import { api } from "@/src/api";
import { isCapabilityEnabled } from "@/src/utils/capabilities";

export default function PosSessionsScreen() {
  const theme = useTheme(); const styles = useMemo(() => makeStyles(theme), [theme]); const router = useRouter();
  const [settings, setSettings] = useState<any>({}); const [locations, setLocations] = useState<any[]>([]); const [sessions, setSessions] = useState<any[]>([]); const [locationId, setLocationId] = useState(""); const [registerName, setRegisterName] = useState("Register 1"); const [openingCash, setOpeningCash] = useState(""); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { const [s, l, p] = await Promise.all([api.getSettings(), api.listLocations(), api.listPosSessions()]); setSettings(s); setLocations(l.filter((item: any) => item.active !== false)); setSessions(p); if (!locationId && l[0]) setLocationId(l[0].id); } catch (error: any) { Alert.alert("Could not load POS sessions", error?.message || "Try again."); } finally { setLoading(false); } }, [locationId]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const openSession = async () => { const amount = Number(openingCash || 0); if (!locationId) return Alert.alert("Choose a location", "Add a store or warehouse first."); if (!Number.isFinite(amount) || amount < 0) return Alert.alert("Check opening cash", "Enter zero or a valid opening amount."); setSaving(true); try { const session = await api.createPosSession({ locationId, registerName: registerName.trim() || "Register 1", openingCash: amount, openedAt: new Date().toISOString(), status: "open" }); setSessions((current) => [session, ...current]); setOpeningCash(""); } catch (error: any) { Alert.alert("Could not open session", error?.message || "Try again."); } finally { setSaving(false); } };
  const closeSession = async (session: any) => { Alert.alert("Close POS session?", "Closing records the drawer as complete. You can still review the session later.", [{ text: "Cancel", style: "cancel" }, { text: "Close session", onPress: async () => { try { const updated = await api.closePosSession(session.id); setSessions((current) => current.map((item) => item.id === session.id ? updated : item)); } catch (error: any) { Alert.alert("Could not close session", error?.message || "Try again."); } } }]); };
  if (!loading && !isCapabilityEnabled(settings, "multi_location")) return <SafeAreaView style={styles.container}><View style={styles.center}><Ionicons name="cash-outline" size={40} color={theme.color.brandPrimary} /><Text style={styles.title}>POS sessions are off</Text><Text style={styles.sub}>Enable Multi-location retail from Settings to open drawers by store.</Text><Pressable onPress={() => router.replace("/customize-features")} style={styles.primary}><Text style={styles.primaryText}>Open capabilities</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={styles.container} edges={["top"]}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={23} color={theme.color.onSurface} /></Pressable><View style={{ flex: 1 }}><Text style={styles.headerTitle}>POS sessions</Text><Text style={styles.headerSub}>Open and close each drawer separately.</Text></View></View><ScrollView contentContainerStyle={styles.content}><View style={styles.formCard}><Text style={styles.sectionTitle}>Open a drawer</Text><TextInput value={registerName} onChangeText={setRegisterName} placeholder="Register name" placeholderTextColor={theme.color.muted} style={styles.input} /><TextInput value={openingCash} onChangeText={setOpeningCash} placeholder="Opening cash" placeholderTextColor={theme.color.muted} keyboardType="decimal-pad" style={styles.input} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, marginBottom: 12 }}>{locations.map((location) => <Pressable key={location.id} onPress={() => setLocationId(location.id)} style={[styles.locationChip, locationId === location.id && styles.locationSelected]}><Ionicons name="storefront-outline" size={15} color={locationId === location.id ? theme.color.brandPrimary : theme.color.muted} /><Text style={[styles.locationText, locationId === location.id && { color: theme.color.brandPrimary }]}>{location.name}</Text></Pressable>)}</ScrollView><Pressable onPress={openSession} disabled={saving || !locationId} style={[styles.primary, (saving || !locationId) && { opacity: 0.5 }]}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.primaryText}>Open session</Text>}</Pressable></View><Text style={styles.sectionTitle}>Recent sessions</Text>{sessions.length === 0 ? <View style={styles.empty}><Ionicons name="receipt-outline" size={28} color={theme.color.muted} /><Text style={styles.emptyTitle}>No sessions yet</Text><Text style={styles.sub}>Opening a drawer creates a location-aware operational record.</Text></View> : sessions.map((session) => { const location = locations.find((item) => item.id === session.locationId); const isOpen = session.status !== "closed"; return <View key={session.id} style={styles.sessionCard}><View style={styles.sessionIcon}><Ionicons name={isOpen ? "lock-open-outline" : "lock-closed-outline"} size={21} color={isOpen ? theme.color.success : theme.color.muted} /></View><View style={{ flex: 1 }}><Text style={styles.sessionName}>{session.registerName || "Register"} · {location?.name || "Unknown location"}</Text><Text style={styles.sessionSub}>Opening cash {Number(session.openingCash || 0).toFixed(2)} · {isOpen ? "Open" : "Closed"}</Text></View>{isOpen && <Pressable onPress={() => closeSession(session)} style={styles.closeButton}><Text style={styles.closeText}>Close</Text></Pressable>}</View>; })}</ScrollView></SafeAreaView>;
}
function makeStyles(theme: any) { return StyleSheet.create({ container: { flex: 1, backgroundColor: theme.color.surface }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 28 }, title: { color: theme.color.onSurface, fontSize: 20, fontWeight: "800", marginTop: 14, textAlign: "center" }, sub: { color: theme.color.muted, fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 7 }, header: { flexDirection: "row", alignItems: "center", gap: 10, padding: 16, borderBottomWidth: 1, borderBottomColor: theme.color.border }, back: { padding: 4 }, headerTitle: { color: theme.color.onSurface, fontSize: 18, fontWeight: "800" }, headerSub: { color: theme.color.muted, fontSize: 11, marginTop: 2 }, content: { padding: 16, paddingBottom: 40 }, formCard: { padding: 15, borderRadius: 18, backgroundColor: theme.color.surfaceSecondary, borderWidth: 1, borderColor: theme.color.border, marginBottom: 22 }, sectionTitle: { color: theme.color.onSurface, fontSize: 15, fontWeight: "800", marginBottom: 10 }, input: { borderWidth: 1, borderColor: theme.color.border, borderRadius: 13, padding: 12, color: theme.color.onSurface, backgroundColor: theme.color.surface, marginBottom: 9 }, primary: { backgroundColor: theme.color.brandPrimary, padding: 13, borderRadius: 13, alignItems: "center" }, primaryText: { color: "#fff", fontWeight: "800" }, locationChip: { flexDirection: "row", alignItems: "center", gap: 5, paddingVertical: 9, paddingHorizontal: 11, borderRadius: 14, borderWidth: 1, borderColor: theme.color.border }, locationSelected: { borderColor: theme.color.brandPrimary, backgroundColor: theme.color.brandPrimary + "12" }, locationText: { color: theme.color.muted, fontSize: 12, fontWeight: "700" }, empty: { alignItems: "center", padding: 28, borderWidth: 1, borderColor: theme.color.border, borderRadius: 18, borderStyle: "dashed" }, emptyTitle: { color: theme.color.onSurface, fontWeight: "800", marginTop: 8 }, sessionCard: { flexDirection: "row", alignItems: "center", gap: 10, padding: 14, borderRadius: 16, backgroundColor: theme.color.surfaceSecondary, borderWidth: 1, borderColor: theme.color.border, marginBottom: 9 }, sessionIcon: { width: 40, height: 40, borderRadius: 20, justifyContent: "center", alignItems: "center", backgroundColor: theme.color.surface }, sessionName: { color: theme.color.onSurface, fontWeight: "800", fontSize: 13 }, sessionSub: { color: theme.color.muted, fontSize: 11, marginTop: 3 }, closeButton: { paddingVertical: 8, paddingHorizontal: 11, borderRadius: 12, borderWidth: 1, borderColor: theme.color.border }, closeText: { color: theme.color.onSurface, fontWeight: "800", fontSize: 11 } }); }
