import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { api } from '@/src/api';
import { ScreenHeader } from '@/src/components/UI';
import { useTheme } from '@/src/context/ThemeContext';

type Stage = 'idle' | 'publish_initial_snapshot' | 'install_validated_snapshot' | 'ready_for_sync';
export default function PrivateSyncMigrationScreen() {
  const theme = useTheme();
  const styles = useMemo(() => makeStyles(theme), [theme]);
  const [serverUrl, setServerUrl] = useState(''); const [userId, setUserId] = useState(''); const [token, setToken] = useState('');
  const [prerequisites, setPrerequisites] = useState<any>(null); const [stage, setStage] = useState<Stage>('idle'); const [pending, setPending] = useState(0); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const [next, status] = await Promise.all([api.getPrivateSyncPrerequisites(), api.getSyncStatus()]); setPrerequisites(next); setPending(Number(status.pending || 0) + Number(status.retryable || 0)); if (status.serverUrl) setServerUrl((current) => current || String(status.serverUrl)); if (status.userId) setUserId((current) => current || String(status.userId)); } catch (error: any) { setMessage(error?.message || 'Migration prerequisites are unavailable.'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const start = async () => { setBusy(true); setMessage(''); try { const result = await api.migrateToPrivateSync({ serverUrl, userId, accessToken: token }); setPending(result.preservedPending); setStage(result.stage as Stage); setToken(''); setMessage(result.stage === 'publish_initial_snapshot' ? 'The server is empty. Review the destination and explicitly publish this local book as the initial canonical snapshot.' : result.stage === 'install_validated_snapshot' ? 'The server already has canonical data. Install the validated server snapshot before replaying preserved local work.' : 'Migration completed without replacing local data. Private sync is ready.'); await load(); } catch (error: any) { setMessage(error?.message || 'Migration stopped before changing the local book.'); } finally { setBusy(false); } };
  const publish = () => Alert.alert('Publish this local book?', 'This makes the reviewed local book the initial canonical snapshot for the user-owned server. No raw SQLite file is uploaded.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Publish', onPress: () => void perform(async () => { await api.publishSyncSnapshot(); setStage('ready_for_sync'); }, 'Initial snapshot published. Private sync is ready.') }]);
  const install = () => void perform(async () => { await api.installSyncSnapshot(); }, 'Validated server snapshot installed and preserved local work replayed.');
  const perform = async (action: () => Promise<void>, success: string) => { setBusy(true); setMessage(''); try { await action(); setMessage(success); await load(); } catch (error: any) { setMessage(error?.message || 'The migration step failed; local data was not destructively replaced.'); } finally { setBusy(false); } };
  const leave = () => Alert.alert('Return to Local-only mode?', 'Private sync will be disabled on this device. Local data and pending work remain; the server is not deleted.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Continue', onPress: () => void perform(() => api.leavePrivateSync(), 'Private sync disabled. This device is back in Local-only mode.') }]);
  const ready = prerequisites?.integrity?.ok && prerequisites?.hasRecentEncryptedBackup;
  return <SafeAreaView style={styles.container} edges={['top']}><ScreenHeader title="Move to Private sync" subtitle="Guided migration without raw database replacement" leftAction={<Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={theme.color.onSurface} /></Pressable>} /><ScrollView contentContainerStyle={styles.scroll}>
    <View style={styles.card}><View style={styles.row}><Ionicons name="shield-checkmark-outline" size={22} color={ready ? theme.color.success : theme.color.warning || theme.color.brandPrimary} /><Text style={styles.title}>Migration prerequisites</Text></View><Text style={styles.hint}>{prerequisites?.integrity?.ok ? 'Local book integrity passed.' : 'Local integrity check is required before migration.'}</Text><Text style={styles.hint}>{prerequisites?.hasRecentEncryptedBackup ? 'A recent verified encrypted backup is available.' : 'Create and verify an encrypted backup first.'}</Text><Text style={styles.hint}>Pending local work preserved: {pending}</Text></View>
    <View style={styles.card}><Text style={styles.title}>Connect your own server</Text><Text style={styles.hint}>Ledgr writes locally first. This flow configures the user-owned server, enrolls this device, and then asks you to publish or recover explicitly. It never silently overwrites the local book.</Text><Text style={styles.label}>Server URL</Text><TextInput value={serverUrl} onChangeText={setServerUrl} autoCapitalize="none" keyboardType="url" placeholder="https://sync.example.com" placeholderTextColor={theme.color.muted} style={styles.input} /><Text style={styles.label}>Account or user ID</Text><TextInput value={userId} onChangeText={setUserId} autoCapitalize="none" placeholder="you@example.com" placeholderTextColor={theme.color.muted} style={styles.input} /><Text style={styles.label}>Manual access token</Text><TextInput value={token} onChangeText={setToken} autoCapitalize="none" secureTextEntry placeholder="Used only for this migration request" placeholderTextColor={theme.color.muted} style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel="Start safe private sync migration" disabled={busy || !ready || !serverUrl.trim() || !userId.trim() || !token.trim()} onPress={() => void start()} style={[styles.primary, (busy || !ready || !serverUrl.trim() || !userId.trim() || !token.trim()) && styles.disabled]}><Text style={styles.primaryText}>{busy ? 'Working…' : 'Start safe migration'}</Text></Pressable></View>
    {stage !== 'idle' ? <View style={styles.card}><Text style={styles.title}>Next explicit step</Text>{stage === 'publish_initial_snapshot' ? <><Text style={styles.hint}>The server epoch is empty. Confirm that this local book is the intended source of truth, then publish the initial snapshot.</Text><Pressable accessibilityRole="button" accessibilityLabel="Review and publish initial snapshot" disabled={busy} onPress={publish} style={styles.secondary}><Text style={styles.secondaryText}>Review and publish initial snapshot</Text></Pressable></> : stage === 'install_validated_snapshot' ? <><Text style={styles.hint}>The server has canonical data. Validate and install its snapshot; preserved local operations remain auditable and are replayed only after validation.</Text><Pressable accessibilityRole="button" accessibilityLabel="Install validated server snapshot" disabled={busy} onPress={install} style={styles.secondary}><Text style={styles.secondaryText}>Install validated server snapshot</Text></Pressable></> : <Text style={styles.success}>Private sync is ready. Local writes remain available if the server is unavailable.</Text>}</View> : null}
    <View style={styles.boundary}><Text style={styles.boundaryTitle}>Three separate concepts</Text><Text style={styles.hint}><Text style={styles.bold}>Encrypted backup</Text> is portable recovery. <Text style={styles.bold}>Private sync</Text> coordinates validated operations across your devices. A <Text style={styles.bold}>future hosted ERP</Text> would be a different product and is not required here.</Text></View>
    <Pressable accessibilityRole="button" accessibilityLabel="Return this device to Local-only mode" disabled={busy} onPress={leave} style={styles.leave}><Text style={styles.leaveText}>Return this device to Local-only mode</Text></Pressable>{message ? <Text style={styles.message}>{message}</Text> : null}
  </ScrollView></SafeAreaView>;
}
const makeStyles = (theme: any) => StyleSheet.create({ container: { flex: 1, backgroundColor: theme.color.surface }, scroll: { padding: theme.spacing.lg, gap: 14, paddingBottom: 48 }, card: { backgroundColor: theme.color.surfaceSecondary, borderColor: theme.color.border, borderWidth: 1, borderRadius: theme.radius.lg, padding: 17, gap: 8 }, row: { flexDirection: 'row', alignItems: 'center', gap: 9 }, title: { color: theme.color.onSurface, fontWeight: '800', fontSize: 18 }, hint: { color: theme.color.muted, fontSize: 13, lineHeight: 19 }, label: { color: theme.color.onSurface, fontWeight: '700', fontSize: 12, marginTop: 7 }, input: { color: theme.color.onSurface, backgroundColor: theme.color.surface, borderColor: theme.color.border, borderWidth: 1, borderRadius: theme.radius.md, paddingHorizontal: 11, paddingVertical: 11 }, primary: { backgroundColor: theme.color.brandPrimary, borderRadius: theme.radius.md, padding: 13, alignItems: 'center', marginTop: 10 }, primaryText: { color: theme.color.onBrandPrimary, fontWeight: '800' }, disabled: { opacity: 0.45 }, secondary: { borderColor: theme.color.brandPrimary, borderWidth: 1, borderRadius: theme.radius.md, padding: 12, alignItems: 'center', marginTop: 7 }, secondaryText: { color: theme.color.brandPrimary, fontWeight: '800' }, boundary: { backgroundColor: theme.color.surfaceTertiary, borderColor: theme.color.border, borderWidth: 1, borderRadius: theme.radius.md, padding: 14, gap: 5 }, boundaryTitle: { color: theme.color.onSurface, fontWeight: '800' }, bold: { fontWeight: '800', color: theme.color.onSurface }, leave: { padding: 13, alignItems: 'center' }, leaveText: { color: theme.color.error || '#c53b3b', fontWeight: '700' }, success: { color: theme.color.success || theme.color.brandPrimary, fontWeight: '700', lineHeight: 20 }, message: { color: theme.color.muted, fontSize: 13, lineHeight: 19 } });
