import React, { useMemo } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { ScreenHeader } from '@/src/components/UI';
import { useTheme } from '@/src/context/ThemeContext';

const sections = [
  { number: '1', title: 'Keep using Ledgr', text: 'Your work is saved on this device first. You can record sales, expenses, payments, purchases, and stock even when the internet is off.' },
  { number: '2', title: 'Make a locked copy', text: 'Open Backup & Recovery and export an encrypted backup. Choose a passphrase you will remember. Keep the file and passphrase separate.' },
  { number: '3', title: 'Share with more devices', text: 'Use Private sync only when an owner, accountant, shop tablet, POS, or warehouse device needs the same business book.' },
  { number: '4', title: 'Choose the easy path', text: 'Joining an existing business uses a short one-time code from the administrator. Setting up your own server opens the guided setup.' },
  { number: '5', title: 'Read before you say yes', text: 'Ledgr checks the backup, business identity, and server before sharing anything. It will stop if something looks wrong.' },
  { number: '6', title: 'If something is waiting', text: 'Open Sync Health. Waiting work is safe on this device. Retry later when the server is back. A conflict means Ledgr needs a person to choose the safe accounting result.' },
];

export default function PrivateSyncGuideScreen() {
  const theme = useTheme(); const styles = useMemo(() => makeStyles(theme), [theme]);
  return <SafeAreaView style={styles.container} edges={['top']}><ScreenHeader title="Simple guide" subtitle="Backups and Private sync" leftAction={<Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={theme.color.onSurface} /></Pressable>} /><ScrollView contentContainerStyle={styles.scroll}><View style={styles.hero}><Text style={styles.heroTitle}>Think of your business book like a notebook.</Text><Text style={styles.heroText}>Local-only mode keeps the notebook on your device. An encrypted backup is a locked copy. Private sync lets approved devices share checked changes.</Text></View>{sections.map((section) => <View key={section.number} style={styles.card}><View style={styles.number}><Text style={styles.numberText}>{section.number}</Text></View><View style={styles.copy}><Text style={styles.title}>{section.title}</Text><Text style={styles.text}>{section.text}</Text></View></View>)}<View style={styles.remember}><Text style={styles.rememberTitle}>Remember these three things</Text><Text style={styles.text}>1. Local work comes first.</Text><Text style={styles.text}>2. Backup and sync are different.</Text><Text style={styles.text}>3. Read the message before you confirm.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Open private sync setup" onPress={() => router.back()} style={styles.primary}><Text style={styles.primaryText}>Go to Private sync</Text></Pressable><View style={{ height: 32 }} /></ScrollView></SafeAreaView>;
}

const makeStyles = (theme: any) => StyleSheet.create({ container: { flex: 1, backgroundColor: theme.color.surface }, scroll: { padding: theme.spacing.lg, gap: 11, paddingBottom: 38 }, hero: { backgroundColor: theme.color.surfaceTertiary, borderColor: theme.color.border, borderWidth: 1, borderRadius: theme.radius.lg, padding: 17, gap: 7 }, heroTitle: { color: theme.color.onSurface, fontSize: 20, lineHeight: 26, fontWeight: '800' }, heroText: { color: theme.color.muted, fontSize: 14, lineHeight: 20 }, card: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, backgroundColor: theme.color.surfaceSecondary, borderColor: theme.color.border, borderWidth: 1, borderRadius: theme.radius.md, padding: 14 }, number: { width: 28, height: 28, borderRadius: 14, backgroundColor: theme.color.brandPrimary, alignItems: 'center', justifyContent: 'center' }, numberText: { color: theme.color.onBrandPrimary, fontWeight: '800' }, copy: { flex: 1, gap: 4 }, title: { color: theme.color.onSurface, fontSize: 15, fontWeight: '800' }, text: { color: theme.color.muted, fontSize: 13, lineHeight: 19 }, remember: { backgroundColor: theme.color.surfaceSecondary, borderColor: theme.color.brandPrimary, borderWidth: 1, borderRadius: theme.radius.lg, padding: 16, gap: 5 }, rememberTitle: { color: theme.color.brandPrimary, fontWeight: '800', fontSize: 16, marginBottom: 3 }, primary: { backgroundColor: theme.color.brandPrimary, borderRadius: theme.radius.md, paddingVertical: 13, alignItems: 'center', marginTop: 3 }, primaryText: { color: theme.color.onBrandPrimary, fontWeight: '800' } });
