import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { api } from '@/src/api';
import { ScreenHeader } from '@/src/components/UI';
import { useTheme } from '@/src/context/ThemeContext';

export default function SyncSettingsScreen() {
  const theme = useTheme();
  const styles = useMemo(() => makeStyles(theme), [theme]);
  const [serverUrl, setServerUrl] = useState('');
  const [userId, setUserId] = useState('');
  const [token, setToken] = useState('');
  const [status, setStatus] = useState<any>(null);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setStatus(await api.getSyncStatus()); } catch (error: any) { setMessage(error?.message || 'Sync is unavailable until SQLite is ready.'); } }, []);
  useEffect(() => { load(); }, [load]);
  const enroll = async () => { setBusy(true); setMessage(''); try { await api.configureSync({ serverUrl, userId, accessToken: token, enabled: true }); setToken(''); setMessage('Sync enabled for this Business Account. Local writes remain available offline.'); await load(); } catch (error: any) { setMessage(error?.message || 'Could not enable sync.'); } finally { setBusy(false); } };
  const syncNow = async () => { setBusy(true); setMessage(''); try { const next = await api.syncNow(); setStatus(next); setMessage('Sync completed.'); } catch (error: any) { setMessage(error?.message || 'Sync could not reach the server; local data is unchanged.'); } finally { setBusy(false); } };
  const disable = async () => { setBusy(true); setMessage(''); try { await api.disableSync(); setMessage('Sync disabled. Pending local work is retained for recovery.'); await load(); } catch (error: any) { setMessage(error?.message || 'Could not disable sync.'); } finally { setBusy(false); } };
  return <SafeAreaView style={styles.container} edges={['top']}><View style={styles.header}><Pressable onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={theme.color.onSurface} /></Pressable><ScreenHeader title="Self-hosted Sync" subtitle="Optional offline-first collaboration" /></View><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><View style={styles.card}><Text style={styles.title}>Your device stays local first</Text><Text style={styles.hint}>Ledgr writes to this device immediately. When enabled, durable semantic operations are uploaded to your server and replayed on other enrolled devices.</Text><Text style={styles.label}>Server URL</Text><TextInput value={serverUrl} onChangeText={setServerUrl} autoCapitalize="none" keyboardType="url" placeholder="https://sync.example.com" placeholderTextColor={theme.color.muted} style={styles.input} /><Text style={styles.label}>Account or user ID</Text><TextInput value={userId} onChangeText={setUserId} autoCapitalize="none" placeholder="you@example.com" placeholderTextColor={theme.color.muted} style={styles.input} /><Text style={styles.label}>Access token</Text><TextInput value={token} onChangeText={setToken} autoCapitalize="none" secureTextEntry placeholder="Stored only in SecureStore" placeholderTextColor={theme.color.muted} style={styles.input} /><Pressable disabled={busy || !serverUrl.trim() || !userId.trim() || !token.trim()} onPress={enroll} style={[styles.primary, (busy || !serverUrl.trim() || !userId.trim() || !token.trim()) && styles.disabled]}><Text style={styles.primaryText}>{busy ? 'Working…' : status?.enabled ? 'Update enrollment' : 'Enable sync'}</Text></Pressable>{status?.configured ? <View style={styles.status}><Text style={styles.statusTitle}>{status.enabled ? 'Sync enabled' : 'Sync disabled'}</Text><Text style={styles.hint}>{status.pending} pending operation(s) · {status.conflicts} conflict(s)</Text><View style={styles.row}><Pressable disabled={busy || !status.enabled} onPress={syncNow} style={styles.secondary}><Text style={styles.secondaryText}>Sync now</Text></Pressable><Pressable disabled={busy || !status.enabled} onPress={disable} style={styles.secondary}><Text style={styles.secondaryText}>Disable</Text></Pressable></View></View> : null}{message ? <Text style={styles.message}>{message}</Text> : null}</View></ScrollView></SafeAreaView>;
}

const makeStyles = (theme: any) => StyleSheet.create({ container: { flex: 1, backgroundColor: theme.color.surface }, header: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingHorizontal: theme.spacing.lg, paddingTop: 16 }, scroll: { padding: theme.spacing.lg, paddingBottom: 40 }, card: { backgroundColor: theme.color.surfaceSecondary, borderColor: theme.color.border, borderWidth: 1, borderRadius: theme.radius.lg, padding: 18, gap: 8 }, title: { color: theme.color.onSurface, fontSize: 18, fontWeight: '700' }, hint: { color: theme.color.muted, fontSize: 13, lineHeight: 19 }, label: { color: theme.color.onSurface, fontSize: 13, fontWeight: '600', marginTop: 12 }, input: { color: theme.color.onSurface, backgroundColor: theme.color.surface, borderColor: theme.color.border, borderWidth: 1, borderRadius: theme.radius.md, paddingHorizontal: 12, paddingVertical: 11 }, primary: { backgroundColor: theme.color.brandPrimary, borderRadius: theme.radius.md, paddingVertical: 13, alignItems: 'center', marginTop: 16 }, primaryText: { color: theme.color.onBrandPrimary, fontWeight: '700' }, disabled: { opacity: 0.45 }, status: { borderTopColor: theme.color.border, borderTopWidth: 1, marginTop: 18, paddingTop: 14, gap: 6 }, statusTitle: { color: theme.color.brandPrimary, fontWeight: '700' }, row: { flexDirection: 'row', gap: 10, marginTop: 8 }, secondary: { borderColor: theme.color.border, borderWidth: 1, borderRadius: theme.radius.md, paddingHorizontal: 16, paddingVertical: 10 }, secondaryText: { color: theme.color.onSurface, fontWeight: '600' }, message: { color: theme.color.muted, fontSize: 13, marginTop: 10 } });
