import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Card, ScreenHeader } from "@/src/components/UI";
import { GlowPressable } from "@/src/components/GlowPressable";
import { useTheme } from "@/src/context/ThemeContext";
import { activeBookId, activeSqlRunner } from "@/src/db/backend";
import { listOpenSyncConflicts, markSyncConflictResolved, type SyncConflict } from "@/src/sync/conflicts";

export default function SyncConflictsScreen() {
  const theme = useTheme(); const styles = useMemo(() => makeStyles(theme), [theme]); const [items, setItems] = useState<SyncConflict[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (refresh = false) => { if (refresh) setRefreshing(true); else setLoading(true); try { const db = activeSqlRunner(); setItems(db ? await listOpenSyncConflicts(db, activeBookId()) : []); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const resolve = async (id: string) => { const db = activeSqlRunner(); if (!db) return; await markSyncConflictResolved(db, id); await load(true); };
  return <SafeAreaView style={styles.container} edges={["top"]}><ScreenHeader title="Conflict Inbox" subtitle={`${items.length} open item${items.length === 1 ? "" : "s"}`} leftAction={<Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={theme.color.onSurface} /></Pressable>} />{loading ? <ActivityIndicator style={{ marginTop: 40 }} color={theme.color.brandPrimary} /> : <ScrollView contentContainerStyle={styles.scroll} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={theme.color.brandPrimary} />}>{items.length === 0 ? <Card style={styles.card}><Ionicons name="checkmark-circle-outline" size={34} color={theme.color.success} /><Text style={styles.emptyTitle}>No open conflicts</Text><Text style={styles.body}>When synchronization is active, conflicting edits will appear here for review. Ledgr will never silently overwrite accounting data.</Text></Card> : items.map((item) => <Card key={item.conflictId} style={styles.card}><View style={styles.row}><Ionicons name="warning-outline" size={22} color={theme.color.warning || theme.color.brandPrimary} /><View style={{ flex: 1 }}><Text style={styles.title}>{item.reason}</Text><Text style={styles.meta}>Operation {item.opId.slice(0, 12)}… · {new Date(item.createdAt).toLocaleString()}</Text></View></View><Text style={styles.body}>This local intent is retained. Review the canonical change in your accounting workflow before resolving this inbox item.</Text><GlowPressable topHighlight={false} haptic onPress={() => void resolve(item.conflictId)} style={styles.resolve}><Text style={styles.resolveText}>Mark reviewed (retain local intent)</Text></GlowPressable></Card>)}<View style={{ height: 90 }} /></ScrollView>}</SafeAreaView>;
}
function makeStyles(theme: any) { return StyleSheet.create({ container: { flex: 1, backgroundColor: theme.color.surface }, scroll: { padding: 18, paddingBottom: 60, gap: 14 }, card: { padding: 18 }, row: { flexDirection: "row", alignItems: "center", gap: 10 }, title: { color: theme.color.onSurface, fontSize: 15, fontWeight: "700" }, meta: { color: theme.color.muted, fontSize: 11, marginTop: 5 }, body: { color: theme.color.muted, fontSize: 13, lineHeight: 19, marginTop: 12 }, emptyTitle: { color: theme.color.onSurface, fontSize: 17, fontWeight: "700", marginTop: 12 }, resolve: { marginTop: 16, borderWidth: 1, borderColor: theme.color.brandPrimary, borderRadius: theme.radius.md, padding: 12, alignItems: "center" }, resolveText: { color: theme.color.brandPrimary, fontSize: 13, fontWeight: "700" } }); }
