import React, { useMemo, useState } from 'react';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { ScreenHeader } from '@/src/components/UI';
import { useTheme } from '@/src/context/ThemeContext';
import { decodeLedgrSyncQrInvite } from '@/src/sync/qrEnrollment';

export default function SyncScanScreen() {
  const theme = useTheme(); const styles = useMemo(() => makeStyles(theme), [theme]);
  const [permission, requestPermission] = useCameraPermissions();
  const [scanned, setScanned] = useState(false); const [raw, setRaw] = useState(''); const [message, setMessage] = useState('');
  const continueWith = (value: string) => {
    try { decodeLedgrSyncQrInvite(value); setMessage(''); router.replace({ pathname: '/sync-settings', params: { invite: encodeURIComponent(value) } } as any); }
    catch (error: any) { setMessage(error?.message || 'That is not a valid Ledgr invitation.'); }
  };
  const cameraAvailable = Platform.OS !== 'web';
  return <SafeAreaView style={styles.container} edges={['top']}><ScreenHeader title="Scan invitation" subtitle="Join your business safely" leftAction={<Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={theme.color.onSurface} /></Pressable>} /><ScrollView contentContainerStyle={styles.scroll}><View style={styles.intro}><Text style={styles.eyebrow}>One-time invitation</Text><Text style={styles.title}>Point the camera at the QR code.</Text><Text style={styles.hint}>The code expires and works once. It does not contain the administrator’s password.</Text></View>{cameraAvailable && permission?.granted ? <View style={styles.cameraFrame}><CameraView barcodeScannerSettings={{ barcodeTypes: ['qr'] }} onBarcodeScanned={scanned ? undefined : ({ data }) => { setScanned(true); continueWith(data); }} style={StyleSheet.absoluteFillObject} /><View pointerEvents="none" style={styles.scanBox} /></View> : <View style={styles.cameraFallback}><Ionicons name="camera-outline" size={38} color={theme.color.brandPrimary} /><Text style={styles.choiceTitle}>{cameraAvailable ? 'Camera permission is needed' : 'Use the paste option on this device'}</Text>{cameraAvailable && permission?.canAskAgain ? <Pressable accessibilityRole="button" onPress={() => void requestPermission()} style={styles.primary}><Text style={styles.primaryText}>Allow camera</Text></Pressable> : null}</View>}<View style={styles.card}><Text style={styles.sectionTitle}>Paste an invitation</Text><Text style={styles.hint}>Use this only if the QR camera is unavailable.</Text><TextInput accessibilityLabel="Paste Ledgr QR invitation" value={raw} onChangeText={setRaw} autoCapitalize="none" autoCorrect={false} multiline placeholder="Paste the invitation text here" placeholderTextColor={theme.color.muted} style={styles.input} /><Pressable accessibilityRole="button" disabled={!raw.trim()} onPress={() => continueWith(raw.trim())} style={[styles.primary, !raw.trim() && styles.disabled]}><Text style={styles.primaryText}>Use this invitation</Text></Pressable></View>{message ? <Text style={styles.message}>{message}</Text> : null}<Text style={styles.hint}>After scanning, review the server address, role, and shop access before joining.</Text></ScrollView></SafeAreaView>;
}

const makeStyles = (theme: any) => StyleSheet.create({ container: { flex: 1, backgroundColor: theme.color.surface }, scroll: { padding: theme.spacing.lg, gap: 13, paddingBottom: 42 }, intro: { gap: 6 }, eyebrow: { color: theme.color.brandPrimary, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8 }, title: { color: theme.color.onSurface, fontSize: 22, lineHeight: 28, fontWeight: '800' }, hint: { color: theme.color.muted, fontSize: 13, lineHeight: 19 }, cameraFrame: { height: 310, borderRadius: theme.radius.lg, overflow: 'hidden', backgroundColor: '#080d0c', borderWidth: 1, borderColor: theme.color.brandPrimary, alignItems: 'center', justifyContent: 'center' }, scanBox: { width: 220, height: 220, borderWidth: 3, borderColor: theme.color.brandPrimary, borderRadius: 18, backgroundColor: 'transparent' }, cameraFallback: { minHeight: 170, borderRadius: theme.radius.lg, borderWidth: 1, borderColor: theme.color.border, backgroundColor: theme.color.surfaceSecondary, alignItems: 'center', justifyContent: 'center', gap: 9, padding: 20 }, card: { backgroundColor: theme.color.surfaceSecondary, borderColor: theme.color.border, borderWidth: 1, borderRadius: theme.radius.lg, padding: 16, gap: 9 }, sectionTitle: { color: theme.color.onSurface, fontSize: 17, fontWeight: '800' }, choiceTitle: { color: theme.color.onSurface, fontSize: 14, fontWeight: '800', textAlign: 'center' }, input: { minHeight: 90, color: theme.color.onSurface, backgroundColor: theme.color.surface, borderColor: theme.color.border, borderWidth: 1, borderRadius: theme.radius.md, padding: 12, textAlignVertical: 'top' }, primary: { backgroundColor: theme.color.brandPrimary, borderRadius: theme.radius.md, paddingVertical: 13, alignItems: 'center', marginTop: 4 }, primaryText: { color: theme.color.onBrandPrimary, fontWeight: '800' }, disabled: { opacity: 0.45 }, message: { color: theme.color.error || '#c53b3b', fontSize: 13, lineHeight: 19 } });
