import React, { useCallback, useState } from 'react';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ScreenHeader, Card } from '@/src/components/UI';
import { useTheme } from '@/src/context/ThemeContext';
import { api } from '@/src/api';
import { showAlert } from '@/src/utils/alerts';

const today = () => new Date().toISOString().slice(0, 10);
function Field({ label, value, onChangeText, placeholder, keyboardType = 'default' }: any) { return <View style={{ marginBottom: 9 }}><Text style={{ fontSize: 11, fontWeight: '700', marginBottom: 4 }}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} keyboardType={keyboardType} style={{ borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 9, fontSize: 13 }} /></View>; }

export default function TradeScreen() {
  const theme = useTheme();
  const [reference, setReference] = useState(''); const [direction, setDirection] = useState<'import' | 'export'>('import'); const [currency, setCurrency] = useState('USD'); const [goodsValue, setGoodsValue] = useState(''); const [rate, setRate] = useState('1');
  const [shipmentId, setShipmentId] = useState(''); const [kind, setKind] = useState('Freight'); const [costAmount, setCostAmount] = useState(''); const [costRate, setCostRate] = useState('1');
  const [fxAccount, setFxAccount] = useState('2000'); const [fxAmount, setFxAmount] = useState(''); const [fxKind, setFxKind] = useState<'gain' | 'loss'>('loss'); const [shipments, setShipments] = useState<any[]>([]); const [costs, setCosts] = useState<any[]>([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const [nextShipments, nextCosts] = await Promise.all([api.listTradeShipments(), api.listTradeCosts()]); setShipments(nextShipments as any[]); setCosts(nextCosts as any[]); } catch { /* no active book yet */ } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const run = async (work: () => Promise<any>, success: string) => { setBusy(true); try { await work(); await load(); showAlert('Saved', success); } catch (error: any) { showAlert('Could not save', error?.message || 'Please review the fields.'); } finally { setBusy(false); } };

  return <SafeAreaView style={{ flex: 1, backgroundColor: theme.color.surface }}><ScreenHeader title="Import / Export" subtitle="Shipments, landed cost, foreign currency, and trade margin" /><ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 36 }}>
    <Card style={{ padding: 14, marginBottom: 14 }}><Text style={{ color: theme.color.brandPrimary, fontWeight: '800', fontSize: 11, textTransform: 'uppercase' }}>1 · Create shipment</Text><Field label="Shipment reference" value={reference} onChangeText={setReference} placeholder="e.g. IMP-2026-001" /><View style={{ flexDirection: 'row', gap: 8, marginBottom: 9 }}><Pressable onPress={() => setDirection('import')} style={{ flex: 1, borderRadius: 10, padding: 10, backgroundColor: direction === 'import' ? theme.color.brandPrimary : theme.color.surfaceSecondary }}><Text style={{ textAlign: 'center', color: direction === 'import' ? '#fff' : theme.color.onSurface, fontWeight: '800' }}>Import</Text></Pressable><Pressable onPress={() => setDirection('export')} style={{ flex: 1, borderRadius: 10, padding: 10, backgroundColor: direction === 'export' ? theme.color.brandPrimary : theme.color.surfaceSecondary }}><Text style={{ textAlign: 'center', color: direction === 'export' ? '#fff' : theme.color.onSurface, fontWeight: '800' }}>Export</Text></Pressable></View><Field label="Currency" value={currency} onChangeText={setCurrency} placeholder="USD" /><Field label="Goods value" value={goodsValue} onChangeText={setGoodsValue} keyboardType="decimal-pad" placeholder="0" /><Field label="Exchange rate" value={rate} onChangeText={setRate} keyboardType="decimal-pad" placeholder="1" /><Pressable disabled={busy} onPress={() => run(() => api.createTradeShipment({ reference, date: today(), direction, currency, goodsValue: Number(goodsValue), exchangeRate: Number(rate) }), 'Shipment created. Add freight, duties, or other landed costs.')} style={{ backgroundColor: theme.color.brandPrimary, borderRadius: 10, padding: 11 }}><Text style={{ color: '#fff', textAlign: 'center', fontWeight: '800' }}>Create shipment</Text></Pressable></Card>
    <Card style={{ padding: 14, marginBottom: 14 }}><Text style={{ color: theme.color.brandPrimary, fontWeight: '800', fontSize: 11, textTransform: 'uppercase' }}>2 · Add landed cost</Text><Field label="Shipment ID" value={shipmentId} onChangeText={setShipmentId} placeholder="Paste the shipment ID" /><Field label="Cost type" value={kind} onChangeText={setKind} placeholder="Freight, duty, port, insurance" /><Field label="Amount" value={costAmount} onChangeText={setCostAmount} keyboardType="decimal-pad" placeholder="0" /><Field label="Exchange rate" value={costRate} onChangeText={setCostRate} keyboardType="decimal-pad" placeholder="1" /><Pressable disabled={busy} onPress={() => run(() => api.addTradeLandedCost({ shipmentId, date: today(), kind, amount: Number(costAmount), currency, exchangeRate: Number(costRate), capitalized: true, method: 'bank' }), 'Landed cost capitalized into inventory.')} style={{ backgroundColor: theme.color.surfaceSecondary, borderWidth: 1, borderColor: theme.color.brandPrimary, borderRadius: 10, padding: 11 }}><Text style={{ color: theme.color.brandPrimary, textAlign: 'center', fontWeight: '800' }}>Capitalize landed cost</Text></Pressable></Card>
    <Card style={{ padding: 14, marginBottom: 14 }}><Text style={{ color: theme.color.brandPrimary, fontWeight: '800', fontSize: 11, textTransform: 'uppercase' }}>3 · FX remeasurement</Text><Field label="Counter account code" value={fxAccount} onChangeText={setFxAccount} placeholder="2000 for Accounts Payable" /><Field label="Amount" value={fxAmount} onChangeText={setFxAmount} keyboardType="decimal-pad" placeholder="0" /><View style={{ flexDirection: 'row', gap: 8, marginBottom: 9 }}><Pressable onPress={() => setFxKind('gain')} style={{ flex: 1, borderRadius: 10, padding: 10, backgroundColor: fxKind === 'gain' ? theme.color.success : theme.color.surfaceSecondary }}><Text style={{ textAlign: 'center', color: fxKind === 'gain' ? '#fff' : theme.color.onSurface, fontWeight: '800' }}>Gain</Text></Pressable><Pressable onPress={() => setFxKind('loss')} style={{ flex: 1, borderRadius: 10, padding: 10, backgroundColor: fxKind === 'loss' ? theme.color.warning : theme.color.surfaceSecondary }}><Text style={{ textAlign: 'center', color: fxKind === 'loss' ? '#fff' : theme.color.onSurface, fontWeight: '800' }}>Loss</Text></Pressable></View><Pressable disabled={busy} onPress={() => run(() => api.recordFxRemeasurement({ date: today(), accountCode: fxAccount, amount: Number(fxAmount), gainLoss: fxKind, currency, exchangeRate: Number(rate), reference }), 'FX remeasurement posted to the FX gain/loss account.')} style={{ backgroundColor: theme.color.success, borderRadius: 10, padding: 11 }}><Text style={{ color: '#fff', textAlign: 'center', fontWeight: '800' }}>Post FX adjustment</Text></Pressable></Card>
    <Text style={{ fontSize: 17, fontWeight: '800', marginBottom: 8 }}>Shipments</Text>{shipments.map((shipment) => <Card key={shipment.id} style={{ padding: 11, marginBottom: 8 }}><Text style={{ fontWeight: '800' }}>{shipment.reference} · {shipment.direction}</Text><Text style={{ color: theme.color.muted, fontSize: 11, marginTop: 3 }}>ID: {shipment.id} · {shipment.currency} {shipment.goods_value} · Landed cost {shipment.landed_cost} · {shipment.status}</Text></Card>)}
    <Text style={{ fontSize: 17, fontWeight: '800', marginTop: 10, marginBottom: 8 }}>Landed costs</Text>{costs.map((cost) => <Card key={cost.id} style={{ padding: 11, marginBottom: 8 }}><Text style={{ fontWeight: '800' }}>{cost.kind} · {cost.currency} {cost.amount}</Text><Text style={{ color: theme.color.muted, fontSize: 11, marginTop: 3 }}>{cost.date} · {cost.capitalized ? 'Capitalized' : 'Expensed'}</Text></Card>)}
  </ScrollView></SafeAreaView>;
}
